steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'git'
    args: ['clone', 'https://github.com/AnupDudhe/studentapp-ui.git']

  - name: 'gcr.io/cloud-builders/mvn:3.8.7-openjdk-11'
    dir: 'studentapp-ui'
    args: ['clean', 'package']

artifacts:
  objects:
    location: 'gs://YOUR-BUCKET-NAME/artifacts/'
    paths:
      - 'studentapp-ui/target/*.war'

options:
  logging: CLOUD_LOGGING_ONLY
