steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'git'
    args: ['clone', 'https://github.com/AnupDudhe/studentapp-ui.git']

  - name: 'gcr.io/cloud-builders/mvn'
    dir: 'studentapp-ui'
    args: ['package']
    env:
      - 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
      - 'MAVEN_OPTS=--enable-preview'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install openjdk-11-jdk -y && \
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
        java -version && mvn package

options:
  logging: CLOUD_LOGGING_ONLY
